vocabtree: MatchesPage Class Reference
MatchesPage Class Reference
MatchesPage class keeps track of query images and their matches, and outputs an html page containing these matches for visualization purposes.
#include <matches_page.hpp>
Public Member Functions
MatchesPage (uint32_t max_matches_per_page=16, uint32_t max_images_per_match=16)
Ctor, max_matches_per_page specified the max number of rows per page, if this is set too high, the web browser might have problems loading the page.
~MatchesPage ()
void add_match (uint32_t query_id, std::vector< uint64_t > &match_ids, const Dataset &dataset, std::shared_ptr< std::vector< int > > validated=nullptr)
Adds a match to the html_strings variable which will be written as html on write().
void write (const std::string &folder) const
Writes out all the html match mages to the input specified folder.
Protected Member Functions
std::string stylesheet () const
std::string header () const
Returns a string containing css stylesheet.
std::string footer () const
Returns a string containing the html header.
std::string navbar (uint32_t cur_page, uint32_t max_pages) const
Returns a string containing the html footer.
std::string pagename (uint32_t cur_page) const
Returns a string containing the navbar needed for pagination.
Protected Attributes
std::vector< std::string > html_strings
Returns a string containing the pagename (ex. matches_00001.html)
uint32_t max_matches_per_page_
Holds the html strings for each match passed into add_match.
uint32_t max_images_per_match_
Detailed Description
MatchesPage class keeps track of query images and their matches, and outputs an html page containing these matches for visualization purposes.
Definition at line 8 of file matches_page.hpp.
Constructor & Destructor Documentation
MatchesPage::MatchesPage (uint32_t max_matches_per_page = 16, uint32_t max_images_per_match = 16)
Ctor, max_matches_per_page specified the max number of rows per page, if this is set too high, the web browser might have problems loading the page.
max_images_per_match specifies the max number of images in each row. If this is set too high, the web browser might have problems loading the page.
Definition at line 10 of file matches_page.cxx.
References max_images_per_match_, and max_matches_per_page_.
{
         max_matches_per_page_ = max_matches_per_page;
         max_images_per_match_ = max_images_per_match;
 }
MatchesPage::~MatchesPage ()
Definition at line 15 of file matches_page.cxx.
{
 }
Member Function Documentation
void MatchesPage::add_match (uint32_t query_id, std::vector< uint64_t > & match_ids, const Dataset & dataset, std::shared_ptr< std::vector< int > > validated = nullptr)
Adds a match to the html_strings variable which will be written as html on write().
The query_id is the id of the image query. match_ids are the ids of the matches. Finally, dataset is used to figure out the image paths. If validated vector is provided, the web page will highlight validated matches, values should be zero if unvalidated,
0 if validated, and < 0 if failed validation. The validation vector can be smaller
than the size of match_ids, in which case it is assumed to correspond to beginning of match_ids.
Definition at line 19 of file matches_page.cxx.
References html_strings, Dataset::image(), Dataset::location(), and max_images_per_match_.
Referenced by bench_oxford(), benchmark_dataset(), and main().
{
         std::stringstream html_string;
         html_string << "<table><tr>";
         html_string << "<td><img src='" << dataset.location(dataset.image(query_id)->location()) << "' /></td><td> </td>";
         for(size_t i=0; i< MIN(match_ids.size(), max_images_per_match_); i++) {
                 std::shared_ptr<Image> image =  dataset.image(match_ids[i]);
                 const std::string &impath = dataset.location(image->location());
                 if(validated == nullptr || i >= validated->size()) {
                         html_string << "<td><img src='" << impath << "' /></td>";
                 } else {
                         std::stringstream borderstr;
                         borderstr << "border: 1px solid " << ((*validated)[i] > 0 ? "green" : ((*validated)[i] == 0 ? "black" : "red"));
                         html_string << "<td><img src='" << impath << "' style='" << borderstr.str() << "' /></td>";
                 }
         }
         html_string << "</tr></table>";
         html_strings.push_back(html_string.str());
 }
std::string MatchesPage::footer () const protected
Returns a string containing the html header.
Definition at line 113 of file matches_page.cxx.
Referenced by write().
{
         std::string footer_str = R"(
                                </body>
                        </html>
                )";
         return footer_str;
 }
std::string MatchesPage::header () const protected
Returns a string containing css stylesheet.
Definition at line 102 of file matches_page.cxx.
Referenced by write().
{
         std::string header_str = R"(
                        <html>
                                <head>
                                        <link rel='stylesheet' type='text/css' href=')" + s_stylesheet_name + R"(' />
                                </head>
                                <body>
                )";
         return header_str;
 }
std::string MatchesPage::navbar (uint32_t cur_page, uint32_t max_pages) const protected
Returns a string containing the html footer.
Definition at line 121 of file matches_page.cxx.
Referenced by write().
{
         std::stringstream navbar_str;
         navbar_str << "<table><tr>";
         for(uint32_t i=0; i<max_pages; i++) {
                 navbar_str << "<td><a href='" << pagename(i) << "'>" << i << "</a></td>";
         }
         navbar_str << "</tr></table>";
         return navbar_str.str();
 }
std::string MatchesPage::pagename (uint32_t cur_page) const protected
Returns a string containing the navbar needed for pagination.
Definition at line 64 of file matches_page.cxx.
Referenced by write().
{
         std::stringstream current_page_name;
         current_page_name << "matches_" << std::setw(5) << std::setfill('0') << cur_page << ".html";
         return current_page_name.str();
 }
std::string MatchesPage::stylesheet () const protected
Definition at line 70 of file matches_page.cxx.
Referenced by write().
{
         std::string stylesheet_str = R"(
                body {
                        margin: 0px;
                        color : #fcfcfc;
                        background: #111;
                        font-size: 14px;
                        font-family: sans-serif;
                }
                table {
                        margin: 5px;
                        border: 2px solid #fcfcfc;
                        border-spacing: 0;
                    border-collapse: collapse;
                }
                a {
                        color: #fff;
                        text-decoration: none;
                        font-weight: bold;
                }
                img {
                        height: 120px;
                }
                )";
         return stylesheet_str;
 }
void MatchesPage::write (const std::string & folder) const
Writes out all the html match mages to the input specified folder.
The first page will look something like folder/matches_00000.html.
Definition at line 40 of file matches_page.cxx.
References filesystem::create_file_directory(), filesystem::file_exists(), footer(), header(), html_strings, max_images_per_match_, max_matches_per_page_, navbar(), pagename(), s_stylesheet_name, stylesheet(), and filesystem::write_text().
Referenced by bench_oxford(), benchmark_dataset(), and main().
{
         if(!filesystem::file_exists(folder)) {
                 filesystem::create_file_directory(folder + "/index.html");
         }
         // style sheet
         const std::string stylesheet_string = this->stylesheet();
         filesystem::write_text(folder + "/" + s_stylesheet_name, stylesheet_string);
         for(size_t i=0; i<html_strings.size(); i+=max_matches_per_page_) {
                 uint32_t cur_page = i / max_images_per_match_;
                 std::stringstream current_page_str;
                 current_page_str << header();
                 current_page_str << navbar(cur_page, html_strings.size() / max_matches_per_page_ + 1);
                 for(size_t j=i; j<MIN(html_strings.size(), i+max_matches_per_page_); j++) {
                         current_page_str << html_strings[j];
                 }
                 current_page_str << footer();
                 filesystem::write_text(folder + "/" + this->pagename(cur_page), current_page_str.str());
         }
 }
Field Documentation
std::vector<std::string> MatchesPage::html_strings protected
Returns a string containing the pagename (ex. matches_00001.html)
Definition at line 39 of file matches_page.hpp.
Referenced by add_match(), and write().
uint32_t MatchesPage::max_images_per_match_ protected
Definition at line 41 of file matches_page.hpp.
Referenced by add_match(), MatchesPage(), and write().
uint32_t MatchesPage::max_matches_per_page_ protected
Holds the html strings for each match passed into add_match.
Definition at line 41 of file matches_page.hpp.
Referenced by MatchesPage(), and write().
The documentation for this class was generated from the following files:
/home/psastras/vocabtree/modules/vis/matches_page.hpp
/home/psastras/vocabtree/modules/vis/matches_page.cxx