vocabtree: SimpleDataset::SimpleImage Class Reference
SimpleDataset::SimpleImage Class Reference
SimpleImage class used with the SimpleDataset class.
#include <dataset.hpp>
Public Member Functions
SimpleImage (const std::string &path, uint64_t imageid)
Constructs a SimpleImage given the Image relative path in the Dataset directory, and a corresponding unique image ID.
std::string feature_path (const std::string &feat_name) const
Returns the corresponding feature path given a feature name (ex. "sift").
std::string location () const
Returns the image location relative to the database data directory.
Public Member Functions inherited from Image
Image (uint64_t image_id)
virtual ~Image ()
All images are assigned a unique id in the dataset.
Protected Attributes
std::string image_path
Additional Inherited Members
Data Fields inherited from Image
uint64_t id
Detailed Description
SimpleImage class used with the SimpleDataset class.
Features are stored in <data_dir>/<feats>/<feat_name>
Definition at line 82 of file dataset.hpp.
Constructor & Destructor Documentation
SimpleDataset::SimpleImage::SimpleImage (const std::string & path, uint64_t imageid)
Constructs a SimpleImage given the Image relative path in the Dataset directory, and a corresponding unique image ID.
Definition at line 126 of file dataset.cxx.
References image_path.
                                                                              : Image(imageid) {
         image_path = path;
 }
Member Function Documentation
std::string SimpleDataset::SimpleImage::feature_path (const std::string & feat_name) const virtual
Returns the corresponding feature path given a feature name (ex. "sift").
Implements Image.
Definition at line 130 of file dataset.cxx.
{
         uint32_t level0 = id >> 20;
         uint32_t level1 = (id - (level0 << 20)) >> 10;
         std::stringstream ss;
         ss << "/feats/" << feat_name << "/" <<
                 std::setw(4) << std::setfill('0') << level0 << "/" <<
                 std::setw(4) << std::setfill('0') << level1 << "/" <<
                 std::setw(9) << std::setfill('0') << id << "." << feat_name;
         return ss.str();
 }
std::string SimpleDataset::SimpleImage::location () const virtual
Returns the image location relative to the database data directory.
Implements Image.
Definition at line 143 of file dataset.cxx.
Referenced by compute_features(), main(), and SimpleDataset::write().
{
         return image_path;
 }
Field Documentation
std::string SimpleDataset::SimpleImage::image_path protected
Definition at line 95 of file dataset.hpp.
Referenced by SimpleImage().
The documentation for this class was generated from the following files:
/home/psastras/vocabtree/modules/utils/dataset.hpp
/home/psastras/vocabtree/modules/utils/dataset.cxx