.TH "/Users/psastras/vocabtree/modules/utils/image.cxx" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/psastras/vocabtree/modules/utils/image.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'image\&.hpp'\fP
.br
\fC#include <utils/filesystem\&.hpp>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
