.TH "Image" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Image \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <image\&.hpp>\fP
.PP
Inherited by \fBSimpleImage\fP, and \fBSimpleImage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBImage\fP (uint64_t image_id)"
.br
.ti -1c
.RI "virtual \fB~Image\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBfeature_path\fP (const std::string &feat_name) const =0"
.br
.ti -1c
.RI "bool \fBload_sift_feature\fP (cv::Mat &data) const "
.br
.ti -1c
.RI "bool \fBload_bow_feature\fP (std::vector< std::pair< uint32_t, float > > &data) const "
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file image\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Image::Image (uint64_timage_id)"

.PP
Definition at line 5 of file image\&.cxx\&.
.PP
.nf
                             { 
        id = imageid;
}
.fi
.SS "Image::~Image ()\fC [virtual]\fP"

.PP
Definition at line 9 of file image\&.cxx\&.
.PP
.nf
{ }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Image::feature_path (const std::string &feat_name) const\fC [pure virtual]\fP"

.PP
Implemented in \fBSimpleImage\fP, and \fBSimpleImage\fP\&.
.PP
Referenced by load_bow_feature(), and load_sift_feature()\&.
.SS "bool Image::load_bow_feature (std::vector< std::pair< uint32_t, float > > &data) const"

.PP
Definition at line 16 of file image\&.cxx\&.
.PP
References feature_path(), and filesystem::load_bow()\&.
.PP
.nf
                                                                              {
        std::string path = feature_path('bow');
        return filesystem::load_bow(path, data);
}
.fi
.SS "bool Image::load_sift_feature (cv::Mat &data) const"

.PP
Definition at line 11 of file image\&.cxx\&.
.PP
References feature_path(), and filesystem::load_cvmat()\&.
.PP
.nf
                                               {
        std::string path = feature_path('sift');
        return filesystem::load_cvmat(path, data);
}
.fi
.SH "Field Documentation"
.PP 
.SS "uint64_t Image::id"

.PP
Definition at line 13 of file image\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
