.TH "InvertedIndex::SearchParams" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvertedIndex::SearchParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inverted_index\&.hpp>\fP
.PP
Inherits \fBSearchParamsBase\fP\&.
.SH "Detailed Description"
.PP 
Definition at line 15 of file inverted_index\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
