.TH "InvertedIndex::TrainParams" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InvertedIndex::TrainParams \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inverted_index\&.hpp>\fP
.PP
Inherits \fBTrainParamsBase\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBnumClusters\fP"
.br
.ti -1c
.RI "uint32_t \fBnumFeatures\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file inverted_index\&.hpp\&.
.SH "Field Documentation"
.PP 
.SS "uint32_t InvertedIndex::TrainParams::numClusters"

.PP
Definition at line 10 of file inverted_index\&.hpp\&.
.PP
Referenced by InvertedIndex::train()\&.
.SS "uint32_t InvertedIndex::TrainParams::numFeatures"

.PP
Definition at line 11 of file inverted_index\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
