.TH "/Users/psastras/vocabtree/modules/search/inverted_index/inverted_index.cxx" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/psastras/vocabtree/modules/search/inverted_index/inverted_index.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'inverted_index\&.hpp'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
