.TH "MatchResultsBase" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MatchResultsBase \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search_base\&.hpp>\fP
.PP
Inherited by \fBInvertedIndex::MatchResults\fP, and \fBVocabTree::MatchResults\fP\&.
.SS "Data Fields"

.in +1c
.ti -1c
.RI "std::vector< uint64_t > \fBmatches\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 20 of file search_base\&.hpp\&.
.SH "Field Documentation"
.PP 
.SS "std::vector<uint64_t> MatchResultsBase::matches"

.PP
Definition at line 21 of file search_base\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
