.TH "SearchBase" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SearchBase \- 
.PP
Abstract class from which all search structures and methods derive from\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <search_base\&.hpp>\fP
.PP
Inherited by \fBInvertedIndex\fP, and \fBVocabTree\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~SearchBase\fP ()"
.br
.ti -1c
.RI "virtual bool \fBtrain\fP (const std::shared_ptr< const \fBTrainParamsBase\fP > &params, const std::vector< std::shared_ptr< const \fBImage\fP > > &examples)=0"
.br
.ti -1c
.RI "std::vector< std::shared_ptr
.br
< \fBMatchResultsBase\fP > > \fBsearch\fP (const std::shared_ptr< \fBSearchParamsBase\fP > &params, const std::vector< std::shared_ptr< const \fBImage\fP > > &examples)"
.br
.ti -1c
.RI "virtual bool \fBload\fP (const std::string &file_path)=0"
.br
.ti -1c
.RI "virtual bool \fBsave\fP (const std::string &file_path) const =0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual std::shared_ptr
.br
< \fBMatchResultsBase\fP > \fBsearch\fP (const std::shared_ptr< const \fBSearchParamsBase\fP > &params, const std::shared_ptr< const \fBImage\fP > &example)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract class from which all search structures and methods derive from\&. 

Each search method must implement train, search, load and save\&. 
.PP
Definition at line 27 of file search_base\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SearchBase::~SearchBase ()\fC [virtual]\fP"

.PP
Definition at line 2 of file search_base\&.cxx\&.
.PP
.nf
{ }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual bool SearchBase::load (const std::string &file_path)\fC [pure virtual]\fP"

.PP
Implemented in \fBInvertedIndex\fP, and \fBVocabTree\fP\&.
.SS "virtual bool SearchBase::save (const std::string &file_path) const\fC [pure virtual]\fP"

.PP
Implemented in \fBInvertedIndex\fP, and \fBVocabTree\fP\&.
.SS "std::vector< std::shared_ptr< \fBMatchResultsBase\fP > > SearchBase::search (const std::shared_ptr< \fBSearchParamsBase\fP > &params, const std::vector< std::shared_ptr< const \fBImage\fP > > &examples)"

.PP
Definition at line 4 of file search_base\&.cxx\&.
.PP
.nf
                                                                                                                                                                                   {
        std::vector< std::shared_ptr<MatchResultsBase> > all_matches;
        for(size_t i=0; i<examples\&.size(); i++) {
                all_matches\&.push_back(search(params, examples[i]));
        }
        return all_matches;
}
.fi
.SS "virtual std::shared_ptr<\fBMatchResultsBase\fP> SearchBase::search (const std::shared_ptr< const \fBSearchParamsBase\fP > &params, const std::shared_ptr< const \fBImage\fP > &example)\fC [protected]\fP, \fC [pure virtual]\fP"

.PP
Implemented in \fBInvertedIndex\fP, and \fBVocabTree\fP\&.
.SS "virtual bool SearchBase::train (const std::shared_ptr< const \fBTrainParamsBase\fP > &params, const std::vector< std::shared_ptr< const \fBImage\fP > > &examples)\fC [pure virtual]\fP"

.PP
Implemented in \fBInvertedIndex\fP, and \fBVocabTree\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
