.TH "/Users/psastras/vocabtree/modules/search/search_base/search_base.hpp" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/psastras/vocabtree/modules/search/search_base/search_base.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <utils/image\&.hpp>\fP
.br
\fC#include <stdint\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <memory>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTrainParamsBase\fP"
.br
.RI "\fIStructure to hold input training parameters (ex\&. #clusters, #examples to consider) \fP"
.ti -1c
.RI "struct \fBSearchParamsBase\fP"
.br
.ti -1c
.RI "struct \fBMatchResultsBase\fP"
.br
.ti -1c
.RI "class \fBSearchBase\fP"
.br
.RI "\fIAbstract class from which all search structures and methods derive from\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
