.TH "/Users/psastras/vocabtree/modules/tests/vocab_tree_simple.cxx" 3 "Wed Nov 6 2013" "Version 0.0.1" "vocabtree" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/psastras/vocabtree/modules/tests/vocab_tree_simple.cxx \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'tests_config\&.hpp'\fP
.br
\fC#include <search/vocab_tree/vocab_tree\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBSimpleImage\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"

.PP
Definition at line 22 of file vocab_tree_simple\&.cxx\&.
.PP
References s_test_data_dir, VocabTree::search(), and VocabTree::train()\&.
.PP
.nf
                                 {

        VocabTree ii;
        std::shared_ptr<VocabTree::TrainParams> train_params = std::make_shared<VocabTree::TrainParams>();
        train_params->depth = 6;
        train_params->split = 4;
        
        std::vector<std::shared_ptr<const Image> > examples(1);
        examples[0] = std::make_shared<const SimpleImage>(s_test_data_dir + '/simple/images/0000\&.jpg', 0);

        ii\&.train(train_params, examples);

        std::shared_ptr<VocabTree::SearchParams> search_params = std::make_shared<VocabTree::SearchParams>();
        std::shared_ptr<VocabTree::MatchResults> match_results = std::static_pointer_cast<VocabTree::MatchResults>(ii\&.search(search_params, examples[0]));


        return 0;
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for vocabtree from the source code\&.
